### ISSUE TITLE
Source Downloads Prior Versions

### ISSUE THREAD

**Issue by RegencySoftware** [rxtur/BlogEngine.NET#103]
Where can I download the source for version 3.2.0.3 ?

**Comment by sqc1999** [comment]
Everything is just on GitHub, you can find the last commit for the version, and simply download it on GitHub.

**Comment by sqc1999** [comment]
The last commit for 3.2.0.3 is f63d9c89b9973b714dd20b3d1b83069ec551ab74, you can download the source of it from this [link](https://github.com/rxtur/BlogEngine.NET/archive/f63d9c89b9973b714dd20b3d1b83069ec551ab74.zip).

**Comment by sqc1999** [comment]
@rxtur I suggest you to create a tag/release for every version on GitHub so that we can easily find the latest release and download previous versions.

**Comment by rxtur** [comment]
I think it used to be an "archive" page on Github listing commits so it was easy to get to specific version. Will check out tags next time.

**Comment by RegencySoftware** [comment]
Thank you sqc1999 and rxtur. I have not used the commit history before. I have it now, thanks again!
