### ISSUE TITLE
Add multiple Authors

### ISSUE THREAD

**Issue by watoo** [rxtur/BlogEngine.NET#125]
Hi,
how can I add multiple authors (admins) as there is no sign up option. 

I wrote these lines
```
<User>
    <UserName>Admin</UserName>
    <Password></Password>
    <Email>post@example.com</Email>
    <LastLoginTime>2007-12-05 20:46:40</LastLoginTime>
</User>
```
in `/app_data/users.xml` but a user is not added. How can I add new user as this is not described in documentation!

**Comment by sqc1999** [comment]
There is settings for multiple users in Web.config: https://github.com/rxtur/BlogEngine.NET/blob/dc0447eed362a831117107123956e6d96471a32c/BlogEngine/BlogEngine.NET/Web.Config#L23-L24. Just change `singleblog` to `multiuser`, then there will be settings for creating and managing users.

**Comment by sqc1999** [comment]
The self registration option won't appear unless you use `multiblog`, but you can edit `enableSelfRegistration` and `selfRegistrationInitialRole` in your database or an XML file under app_data(depending on where you store your data) to configure for this.
