### ISSUE TITLE
Include a js file in entire project

### ISSUE THREAD

**Issue by watoo** [rxtur/BlogEngine.NET#127]
Hi,
I have some script that I wan to included in all pages of website. So where should I place my `site.js` file so that it should be accessible in entire project.

Similarly I want to include one css file that should be accessible in entire project. So where should I place this?

**Details:**
If a place `site.js` in `~/Scripts/site.js`, then it is accessible only in admin panel. and if I place it in `~/Scripts/Auto/site.js` then it is accessible in all website except admin panel.

I have included this file to existing bundles in `BlogEngineConfig.cs`

**Comment by sqc1999** [comment]
It seems that there isn't a single place for adding a js file to the entire website.
But I can give you some information about how js files are added.
For scripts in admin pages: As you've found out, there is a `ScriptBundle` for this. (https://github.com/rxtur/BlogEngine.NET/blob/dc0447eed362a831117107123956e6d96471a32c/BlogEngine/BlogEngine.NET/AppCode/App_Start/BlogEngineConfig.cs#L106-L150)
For blog pages:
Even there is a bundle too (https://github.com/rxtur/BlogEngine.NET/blob/dc0447eed362a831117107123956e6d96471a32c/BlogEngine/BlogEngine.NET/AppCode/App_Start/BlogEngineConfig.cs#L69-L71), but it is not included by default.
This is because `ScriptBundle` is for Razor pages(.cshtml), but the default theme is written in Web Forms(.aspx).
The actual code for including the js files in the `Auto` directory is here: https://github.com/rxtur/BlogEngine.NET/blob/dc0447eed362a831117107123956e6d96471a32c/BlogEngine/BlogEngine.Core/Web/Scripting/PageHeader.cs#L85-L104

So now you have several options to include a js file in the whole website, you can make the decision yourself.

**Comment by watoo** [comment]
Hi, 
thank you for this information. Is there any layout page or a master page that is included in all pages?

**Comment by sqc1999** [comment]
I think there isn't.
As I've mentioned, the blog pages are mainly implemented with Web Forms(.aspx), and the admin pages are implemented with Razor(.cshtml). They use different engines to produce the final output(.html).
So if you don't want write code for the two engines separately, you should use something at a lower level.
I think a ASP.NET Module will be a good choice.

**Comment by watoo** [comment]
Okay, I think including Js file in both admin bundle and user bundle will be an easy way.
So I added `Site.js` in `BlogEngineConfig.cs`  as:

```
// for anonymous users
 bundles.Add(new ScriptBundle("~/Scripts/Auto/js").Include(
                "~/Scripts/Auto/*.js")
                .Include("~/Scripts/Site.js")
            );

// for authenticated users
  bundles.Add(new ScriptBundle("~/Scripts/Auto/jsauth").Include(
                "~/Scripts/Auto/*.js")
                .Include("~/Scripts/Site.js")
            );

// new admin bundles
bundles.Add(
                new ScriptBundle("~/scripts/blogadmin")
                .Include("~/Scripts/jquery-{version}.js")
                .Include("~/Scripts/Site.js")
```

But its only accessible in admin panel. What I'm doing wrong?
I have no understainding of `GetScripts` function.

**Comment by sqc1999** [comment]
I've told you that the `ScriptBundle`s for blog pages won't work, they're for Razor based themes, but the default theme is written with `.aspx`, it does not and can not use the bundles(`~/Scripts/Auto/js` and `~/Scripts/Auto/jsauth`. These two bundles are there just because BlogEngine.NET supports themes baes on Razor.

**Comment by sqc1999** [comment]
I just came up with another solution: put your `site.js` in `~/Scripts/Auto/`, and include in the `~/Scripts/blogadmin` bundle. Then the two engines will read your `site.js` correctly. 😀

**Comment by watoo** [comment]
wow that's great! It worked :) and how can I include css file?

**Comment by sqc1999** [comment]
That's similar, put the css file in `~/Content/Auto`, and add it to the `~/Content/admincss` bundle.

**Comment by watoo** [comment]
Great! thank you so much :)

**Comment by watoo** [comment]
Sorry for disturbing you again. Actually everything is working fine on localhost and my previous build was also working fine. But when I deployed my new code it gives operation timeout (500) error. I can't figure out what could be the possible reason for that?

**Comment by sqc1999** [comment]
The timeout error seems confusing. I am not sure about what happened. Where are you deploying to, a VPS or something else? Did you add your js and css file to your project in Visual Studio?

**Comment by watoo** [comment]
I have deployed on Azure and previous build was working fine. Following fines are changed in this build.
https://i.imgsafe.org/726421ee0e.png

sharpdoor.com is my website link. This time It gave this error:

> 502 - Web server received an invalid response while acting as a gateway or proxy server.

**Comment by sqc1999** [comment]
I have no idea about what is wrong. Could you please send me a copy of your code so that I can do some debugging?

**Comment by watoo** [comment]
Sure. I haven't made any significant change in code. Kindly see this repo:
https://github.com/watoo/BlogEngine

**Comment by sqc1999** [comment]
I failed to reproduce the problem on my PC. And I don't have any experience with Azure. 😢 
The worst thing is, that I can't visit sharpdoor.com! When I tried to visit it, I was redirected to www.dealkar.pk.

**Comment by watoo** [comment]
Oh, actually sharpdoor.com was set to forwarding on dealkar.pk. But I removed that forwarding a week ago. I think that forwarding is still in cache or something like that. Thank you so much for your precious time! I will try to figure out myself :(

**Comment by watoo** [comment]
Hi,
Unfortunately `site.js` is not included in `Account/login.aspx` file. I created site.js in `~/Scripts/Auto/`, and include it in the ~/Scripts/blogadmin bundle. How can I include this file in `Account/login.aspx` page.

**Comment by watoo** [comment]
On live website, in ` /admin/#/custom/widgets ` page. the selected widgets box is not showing. But its working fine on local host. Kindly see image below for console errors.
https://i.imgsafe.org/83b334a0fe.png

Any clue what could be the possible reason?

**Comment by sqc1999** [comment]
For the account pages:
All the blog pages are inherited from `BlogEngine.Core.Web.Controls.BlogBasePage`, and this class calls `BlogEngine.Core.Web.Scripting.PageHeader.Render()` when being loaded, so the files in the `Auto` directory will be loaded.
But account pages are inherited directly from `System.Web.UI.Page`, so it won't use the `Auto` directory.
I think you can just add links to your files in `~/Account/account.master` to load your files.

**Comment by sqc1999** [comment]
For the widget pages:
AFAI, the 404 errors don't matter. They will occur if there some of your widgets don't have a settings page.
Things will be much simpler if I can login into sharpdoor.com, but now I don't have any ideas. I can't reproduce this issue on `localhost` too.

**Comment by watoo** [comment]
okay, I have figured it out. It was due to following line in `web.config`
`<add key="BlogEngine.UsageScenario" value="singleblog" />`

When I change `singleblog` to `multiusers` then the selected widgets in `/admin/#/custom/widgets` are not showing. Everything works fine with `singleblog` :)

**Comment by sqc1999** [comment]
That's strange...

**Comment by sqc1999** [comment]
Oh, I can access sharpdoor.com now!

**Comment by sqc1999** [comment]
It seems that it is something related to your settings stored in `App_Data`.
The data of the widget box is fetched from `http://domain/api/widgets` but sharpdoor.com returns an empty list.

**Comment by watoo** [comment]
That's strange, I haven't made any changes in `App_Data`

**Comment by sqc1999** [comment]
Code that produces output for `/api/widgets` is in `BlogEngine.Core.Data.ViewModels.WidgetVM`. I am trying to figure out the problem by checking its code.

**Comment by sqc1999** [comment]
Oh, I've got some ideas, just need more investigation..

**Comment by sqc1999** [comment]
Do you have access to the trace information produced by `System.Diagnostics.Trace` in your Azure server? I need some way to get debug output.

**Comment by watoo** [comment]
No, I don't have such information. I just know how to deploy web app on azure. If you can provide steps how to do this, i will configure azure server to get the required output.

**Comment by sqc1999** [comment]
Then try this:
Add a `1.cshtml` to the root directory of the website(don't forget to add it to the project file), and deploy your project to Azure.
````html
@using BlogEngine.Core
@using System.Net
@{
	string error = "", html = "";
	try { html = new WebClient().DownloadString(Utils.AbsoluteWebRoot); }
	catch (Exception ex) { error = ex.ToString(); }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
	<div>@Utils.AbsoluteWebRoot</div>
	<div>@error</div>
	<div>@html</div>
</body>
</html>
````
So that I can get output from this page.

**Comment by watoo** [comment]
I added `1.cshtml` in `BlogEngine.Net`. How to add in project file. I have not worked on web forms. I use MVC.

**Comment by sqc1999** [comment]
Maybe you misunderstood my words. Just add the file to `BlogEngine.NET` and deploy.

**Comment by watoo** [comment]
Done. website is deployed.

**Comment by sqc1999** [comment]
`An unexpected error has occurred`, how strange...
Then change 1.cshtml to this.
````html
@using BlogEngine.Core
@using System.Net
@{
	string error = "", html = "", url = "";
	try
	{
		url = Utils.AbsoluteWebRoot.ToString();
		html = new WebClient().DownloadString(Utils.AbsoluteWebRoot);
	}
	catch (Exception ex) { error = ex.ToString(); }
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title></title>
</head>
<body>
	<div>@url</div>
	<div>@error</div>
	<div>@html</div>
</body>
</html>
````
I think there won't be any unhandled exception now.

**Comment by watoo** [comment]
Done

**Comment by sqc1999** [comment]
Then that's even more strange.
`WigetsVM` will download the home page of your website to find out enabled widgets, but your server returned an empty page!

**Comment by watoo** [comment]
Every time i deploy website it does not remember my settings like name of blog and categories. Also the posts added by editor (role) are just visible to editor and administrator. They aren't visible to public. Why?
And if a category is added by editor then only administrator can delete it. That's also strange behavior. Editor should be able to delete his categories.

Below are admin logins for sharpdoor.com, if you want to test it yourself! 
Administrator login:
user: admin
pass: admin

Editor login:
user: Adil 
pass: admin

**Comment by watoo** [comment]
I'm using this repo https://github.com/watoo/TestBlogEngine. In case if you want to see code

**Comment by sqc1999** [comment]
You might not configure your deploy properly, so some settings in `App_Data` is not deployed, and then settings aren't remembered.
Non-public posts may due to a timezone issue. You should set the timezone in your blog settings to where you're in(not where the server in).
Have no idea about why editors can't delete his categories.

**Comment by sqc1999** [comment]
And I can't access sharpdoor.com again. It shows `The domain sharpdoor.com is no longer parked by GoDaddy.`

**Comment by watoo** [comment]
This domain is working fine for me! you can use this url `http://sharpdoor.azurewebsites.net/` instead of `sharpdoor.com`

**Comment by sqc1999** [comment]
The widget box works fine under `sharpdoor.azurewebsites.net`. Is it still broken under `sharpdoor.com`?

**Comment by watoo** [comment]
Omg its working! The following changes I made in this deploy:
I go to each file in `App_data `folder. 
Go to file properties and then set `Copy to output directory `to `Copy always`

**Comment by sqc1999** [comment]
Congratulations!
