### ISSUE TITLE
Using MSSQL many administration menus are missing

### ISSUE THREAD

**Issue by dvprez** [rxtur/BlogEngine.NET#13]
The "Users" section and all sub sections do not appear.
The Advanced Section does not appear under settings.

I want to enable users to register to comment.  Was this removed because I can't find this option on either the SQL or XML admin panels.

![be_xml_adminpanel](https://cloud.githubusercontent.com/assets/15875416/11382502/2cbaf8a8-92d0-11e5-9299-9b914b9149f2.jpg)
![be_sql_adminpanel](https://cloud.githubusercontent.com/assets/15875416/11382503/2cbc1b66-92d0-11e5-924c-f7d4f8c10101.jpg)

**Comment by rxtur** [comment]
This should explain it:
https://github.com/rxtur/BlogEngine.NET/wiki/Configuration

Also, as a reference:
http://www.rtur.net/blog/post/2015/09/08/multiple-blogs-vs-multiple-users
