### ISSUE TITLE
.aspx links broken in 3.3.5.0

### ISSUE THREAD

**Issue by mgieselman** [rxtur/BlogEngine.NET#135]
Links like http://myblog.com/posts/foo.aspx are now extension less ie. http://myblog.com/posts/foo.  Old links to the blog no longer work if .aspx is included.

Is there a fix or work around to support both URL types?

I tried to add a url rewrite section to the web.config but that didn't work.

**Comment by mgieselman** [comment]
If you install the IIS Rewrite module https://www.iis.net/downloads/microsoft/url-rewrite then do an IISReset from the command line and add the following to the web.config then sites linking to the *.aspx blog posts will still work.

```xml
	<rewrite>
        <rules>
            <rule name="RewriteASPX">
                <match url="(.*).aspx" />
                <conditions logicalGrouping="MatchAll">
                    <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                </conditions>
                <action type="Rewrite" url="{R:1}" />
            </rule>
        </rules>
    </rewrite>
```xml

**Comment by goranhell** [comment]
Check the value for <removeextensionsfromurls> in settings.xml

**Comment by mgieselman** [comment]
@goranhell okay, I think you mean "removeextensionsfromurl", which was set to True thanks!

**Comment by goranhell** [comment]
of course, sorry..

**Comment by ugochirico** [comment]
I cannot install url-rewrite because I'm on a shared hosting.
Is there another workaround?
I'm loosing a lot of SEO because links doesn't work anymore. 
Please give me a solution

**Comment by mgieselman** [comment]
@ugochirico did you read the post from goranhell above about removeextensionsfromurl in settings.xml?

**Comment by ugochirico** [comment]
Ok. I fixed it. Now it seems to work.
Many thanks
