### ISSUE TITLE
Set BlogSettings RelatedPosts and EnableRating

### ISSUE THREAD

**Issue by aaronhoffman** [rxtur/BlogEngine.NET#14]
I can not determine the correct way to set the BlogSettings to show/hide RelatedPosts or show/hide the Rating section.

Are these set via the Admin pages or by some other means?

**Comment by rxtur** [comment]
This depends on your theme implementation. There are templates (PostView.aspx and RelatedPosts.aspx) that you can modify to include or exclude any elements.
