### ISSUE TITLE
GET http://[domain]/api/posts/undefined: Guid should contain 32 digits with 4 dashes

### ISSUE THREAD

**Issue by aaronhoffman** [rxtur/BlogEngine.NET#15]
I am seeing this error when I go to publish a new post right after I save the post. The post appears to publish successfully, but this error is logged.

**Comment by scrummie02** [comment]
Wh you edit the post does the UI in the dashboard say updated failed?

Sent from Outlook




On Tue, Dec 1, 2015 at 2:51 PM -0800, "Aaron Hoffman" <notifications@github.com> wrote:












I am seeing this error when I go to publish a new post right after I save the post. The post appears to publish successfully, but this error is logged.

**Comment by rxtur** [comment]
Fixed (missed post id assignment on save in javascript).
