### ISSUE TITLE
error CS1056: 意外的字符“$”

### ISSUE THREAD

**Issue by cyroby** [rxtur/BlogEngine.NET#152]
When I begin to Compile, it will appear error CS1056: 意外的字符“$”.

**Comment by cyroby** [comment]
![error info 1](https://cloud.githubusercontent.com/assets/11662528/25894300/da96955a-35ad-11e7-8d86-8dd9063774fd.png)
![error info 2](https://cloud.githubusercontent.com/assets/11662528/25894301/dab95df6-35ad-11e7-93cd-dea1c871add6.png)

**Comment by Cambridgeport90** [comment]
Curious. You’ll have to provide the text for this so that I can see them.

**Comment by yw80** [comment]
This problem may be the old version Visual Studio does not support the new syntax sugar feature. I suggest you try updating Visual Studio to the latest version.

**Comment by cyroby** [comment]
@Cambridgeport90  It's Chinese language. " 意外的字符" means:" Unexpected character".

**Comment by DDoSolitary** [comment]
@cyroby `$`开头的字符串是C# 6的语法糖，你的Visual Studio太旧了，不支持C# 6，所以报错

**Comment by cyroby** [comment]
@DDoSolitary 我用的Visual Stdio 2013 旗舰版的，如何才能让它支持C sharp 6.0

**Comment by DDoSolitary** [comment]
@cyroby 升级到VS2015/2017，或者在你的项目中安装一下几个NuGet包：
`Microsoft.Net.Compilers`
`Microsoft.CodeDom.Providers.DotNetCompilerPlatform`

**Comment by cyroby** [comment]
@DDoSolitary  OK，谢了。我再安装个VS2017，用它打开就没问题了。
