### ISSUE TITLE
Is BlogEngine Dead?

### ISSUE THREAD

**Issue by almorax** [rxtur/BlogEngine.NET#164]
Hello there,
I have a blog based dotnetblogengine but I wonder if project is dead? Because there is no new version coming up. Also the domain "http://dotnetblogengine.net/" is dead. @rxtur Can you tell us what's going on?

**Comment by rxtur** [comment]
Hopefully [this](http://www.rtur.net/blog/post/2017/07/30/update-on-blogengine-net) answers it.

**Comment by almorax** [comment]
Hmm.. So all we need to work on blogifier and make a tool to export all posts from blogengine to blogifier :)
