### ISSUE TITLE
Can't update posts, use custom themes or update settings when using any DB provider

### ISSUE THREAD

**Issue by scrummie02** [rxtur/BlogEngine.NET#19]
It just said failed.  Nothing shows up in the logs.  When adding posts they add but then say "failed".
I can give you access if you want to see for yourself.

**Comment by rxtur** [comment]
This was answered here: https://blogengine.codeplex.com/discussions/647973

It is general ASP.NET Web API configuration/setup, not specific to application and can't be replicated/tested.

**Comment by scrummie02** [comment]
It actually wasn’t that at all.  If you have URLScan installed it won’t allow those verbs.  You have to do into the .ini for urlscan and enable put/delete verbs.  After that it works.  Alternatively, you can just disable URLScan but that defeats the purpose.
