### ISSUE TITLE
 Custom fields for Post and Page is greyed Out

### ISSUE THREAD

**Issue by kbdavis07** [rxtur/BlogEngine.NET#2]
Custom fields for Post and Page is greyed Out

Just FYI :)

**Comment by rxtur** [comment]
No worries, replacing with new UI, things updated on the fly right now. Will take a week or so to settle down.

**Comment by atiq-cs** [comment]
@rxtur please also update nuget packages. There are some old js files inside `Scripts/Auto` `Scripts/jQuery`, as well as `Scripts/jquery.cookie` is old. Do updating them break any feature? I did an update to all of them and [my blog](http://tech.saoslab.com/) is still working fine.
