### ISSUE TITLE
Multiple jQuery versions

### ISSUE THREAD

**Issue by aaronhoffman** [rxtur/BlogEngine.NET#20]
There appears to be a few different version of jQuery referenced within the BlogEngine.NET project. Here are a list of the files from `git ls-files *jquery*`

    BlogEngine.NET/Scripts/Auto/01-jquery-1.9.1.min.js
    BlogEngine.NET/Scripts/Auto/02-jquery.cookie.js
    BlogEngine.NET/Scripts/Auto/04-jquery-jtemplates.js
    .
    BlogEngine.NET/Scripts/jQuery/01-jquery-1.9.1.min.js
    BlogEngine.NET/Scripts/jQuery/02-jquery.cookie.js
    BlogEngine.NET/Scripts/jQuery/03-jquery.validate.min.js
    BlogEngine.NET/Scripts/jQuery/04-jquery-jtemplates.js
    .
    BlogEngine.NET/Scripts/jquery-2.1.4.intellisense.js
    BlogEngine.NET/Scripts/jquery-2.1.4.js
    BlogEngine.NET/Scripts/jquery-2.1.4.min.js
    BlogEngine.NET/Scripts/jquery-2.1.4.min.map
    .
    BlogEngine.NET/Scripts/jquery-jtemplates.js
    BlogEngine.NET/Scripts/jquery-jtemplates.min.js
    BlogEngine.NET/Scripts/jquery.cookie.js
    BlogEngine.NET/Scripts/jquery.form.js
    BlogEngine.NET/Scripts/jquery.validate-vsdoc.js
    BlogEngine.NET/Scripts/jquery.validate.js
    BlogEngine.NET/Scripts/jquery.validate.min.js
    .
    BlogEngine.NET/admin/editors/bootstrap-wysiwyg/jquery.hotkeys.js
    BlogEngine.NET/setup/upgrade/jquery-2.0.3.min.js

I am using a custom front page `~/FrontPage.aspx` and I can't find a reference to jQuery within the source of that page or in the `site.master` that I'm using within my theme, but it appears that references to the `BlogEngine.NET/Scripts/Auto/*` versions are added to the page somehow.

I've added a second custom page `~/about.aspx` and these references do not appear on that page.

The only other seemingly relevant places that I found jQuery references within the project are within the `/AppCode/App_Start/BlogEngineConfig.cs` class ([here](https://github.com/rxtur/BlogEngine.NET/blob/master/BlogEngine/BlogEngine.NET/AppCode/App_Start/BlogEngineConfig.cs#L41) and [here](https://github.com/rxtur/BlogEngine.NET/blob/master/BlogEngine/BlogEngine.NET/AppCode/App_Start/BlogEngineConfig.cs#L110), but I can't find references to those script bundles anywhere.

How and/or Why is the `BlogEngine.NET/Scripts/Auto/*` version of jQuery being added to my FrontPage?

**Comment by rxtur** [comment]
The older versions (1.9.1) included for older themes, many rely on it automatically loaded by BE.
If your theme does not need it, you can remove scripts from "/Scripts/Auto" and nothing will be added to your theme.
The reason "about" page does not have it probably because you didn't inherit it from BlogBasePage.
