### ISSUE TITLE
Blogroll (opml) can not be configured but shows up in rss/opml

### ISSUE THREAD

**Issue by raisr** [rxtur/BlogEngine.NET#21]
Hi,

in the current version there is no way to configure the blogroll. But in the rss (syndication.axd) the tag "blogChannel:blogRoll" is shown. When i open this url (yoursite/opml.axd) i see the old preconfigured blogroll.

![2015-12-17 00_39_52-opml axd](https://cloud.githubusercontent.com/assets/1333066/11857264/f8af75a0-a456-11e5-8a98-5400d839eb00.png)

**Comment by rxtur** [comment]
That doesn't look like latest, you should have 3 entries there.
Anyway, you can get to blogroll UI via "/admin/#/settings/controls/blogroll" or add blogroll widget ant click "edit" in the widget toolbar - this will load same admin page.
![blogroll](https://cloud.githubusercontent.com/assets/1932785/11886674/56a50bb6-a4f2-11e5-92fe-39f9d7e5dcb6.png)
