### ISSUE TITLE
Admin - all lists should be filtered and paginated in the server side

### ISSUE THREAD

**Issue by danicomas** [rxtur/BlogEngine.NET#22]
Client code should call passing filter parameters and page to the server side via WS.

https://github.com/rxtur/BlogEngine.NET/blob/master/BlogEngine/BlogEngine.NET/admin/app/content/posts/postController.js#L12

**Comment by rxtur** [comment]
It uses "single page application" approach - get all to the client ant then sort/filter/search without making more calls. For this, all lists made light with only absolutely required data. And sure back-end and WS can do paging if you pass number of items to get and skip. Admin passes "0" meaning "get all".

**Comment by danicomas** [comment]
I think it should be reviewed.
