### ISSUE TITLE
Standard theme - Categorylist

### ISSUE THREAD

**Issue by goranhell** [rxtur/BlogEngine.NET#24]
In the new standard theme the 'Show RSS icon' setting doesn't work in the Category list widget.
To sole it I did the following:

in App_Code/Controls/CategoryList.cs, the BindCategories method
in 'if (this.ShowRssIcon) { ... }' either exchange the content or add (to keep compability with other themes):
li.Attributes["class"] = "rss";

in styles.css
change .categorylist ul li a:first-child:before { font-family: 'fontello'; content: '\e814'; color: #f28115; margin-right: 10px; }
to .categorylist ul li.rss a:first-child:before { font-family: 'fontello'; content: '\e814'; color: #f28115; margin-right: 10px; }
(.rss added to the li selector)

**Comment by scrummie02** [comment]
Thanks, I was wondering how to fix this!

**Comment by goranhell** [comment]
Did you hit Ctrl+F5 so all new styles was read from the server?

**Comment by scrummie02** [comment]
I have, here is my .css
/*[18.CategoryList]*/
.categorylist ul li { margin: 0; border-bottom: 2px dotted #DDD; padding: 3px; line-height: 40px; min-height: 40px; }
.categorylist ul li A {color: #444444; }
.categorylist ul li A  img { margin-right:4px;}

**Comment by goranhell** [comment]
add .rss to li in the first row
.categorylist ul li.rss { margin: 0; border-bottom: 2px dotted #DDD; padding: 3px; line-height: 40px; min-height: 40px; }

**Comment by goranhell** [comment]
My solution applies to the new standard theme. What, in your theme, is adding the rss icon?

**Comment by scrummie02** [comment]
Flat blog. 

Sent from Outlook Mobile




On Sat, Jan 9, 2016 at 1:07 AM -0800, "goranhell" <notifications@github.com> wrote:












My solution applies to the new standard theme. What, in your theme, is adding the rss icon?

**Comment by scrummie02** [comment]
Thanks for the help.  Something weird.  It worked for few minutes then it stopped. 

Sent from Outlook Mobile




On Sat, Jan 9, 2016 at 1:07 AM -0800, "goranhell" <notifications@github.com> wrote:












My solution applies to the new standard theme. What, in your theme, is adding the rss icon?

**Comment by rxtur** [comment]
Category widget replaced with new one.
