### ISSUE TITLE
Standard theme - Blogroll

### ISSUE THREAD

**Issue by goranhell** [rxtur/BlogEngine.NET#25]
In the blogroll the Rss icon is added to the items for each blogroll as well.
To solve this I in styles.css changed
.blogroll ul li a:first-child:before { font-family: 'fontello'; content: '\e814'; color: #f28115; margin-right: 10px; }
to
#blogroll > ul > li > a:first-child:before { font-family: 'fontello'; content: '\e814'; color: #f28115; margin-right: 10px; }

**Comment by rxtur** [comment]
Blogroll widget is completely rewritten for 3.3
