### ISSUE TITLE
Various

### ISSUE THREAD

**Issue by goranhell** [rxtur/BlogEngine.NET#26]
My username is 'Göran' and because of the swedish character I couldn't create new post, loading profile and probably more. I solved it by adding Html.Raw around Security.CurrentUser.Identity.Name in
admin\themes\standard\layout.cshtml:
```c#
var UserVars = { Name: '@Html.Raw(@Security.CurrentUser.Identity.Name)', IsAdmin: '@Security.IsAdministrator', Rights: ['@Html.Raw(userRights)'] };
```

After submitting the Contact page the page didn't render correctly (most visible if you have an image in your header), so I changed in BlogEngine.Core\Web\HttpModules\CompressionModule.cs:
Method: ContextPostReleaseRequestState
change
```c#
if (context.CurrentHandler is Page && context.Request["HTTP_X_MICROSOFTAJAX"] == null && context.Request.HttpMethod == "GET")
```
to
```c#
if (context.CurrentHandler is Page && context.Request["HTTP_X_MICROSOFTAJAX"] == null && (context.Request.HttpMethod == "GET" || context.Request.HttpMethod == "POST"))
```

**Comment by rxtur** [comment]
Included with 3.0.0.2
