### ISSUE TITLE
Lack of authentication for save profile API

### ISSUE THREAD

**Issue by jijiechen** [rxtur/BlogEngine.NET#28]
For versions prior to to the coming version, I think at least later than version 3.1, the API for saving profiles lacks of authentication.
The uri of this API is /api/users/saveprofile/item.

Direct result for this problem is an author's profile can be updated anonymously without a credential. 
Many BlogEngine instances had been hacked because of this problem.  They were injected with a code segment with an intend to add a new admin user on next current admin's login.
See the search results: https://www.google.com.hk/search?q=82hv7gdwjxgqw3

Some BlogEngine instances use themes which do not encode profile properly when showing lists or posts, so on those sites, visitors will get login windows due to UnAuthorized injected requests. Other instances are more lucky—they only get ugly encoded injected HTML fragments.

A recent commit fixed this problem.  But the new version is still not released yet.
https://github.com/rxtur/BlogEngine.NET/commit/f63d9c89b9973b714dd20b3d1b83069ec551ab74#diff-b13678340f14127c10bd06d6c385a0faR154

Thank @rxtur for the fix, and expecting next version.

**Comment by rxtur** [comment]
No need for new version, the patch with effected files has been released few days ago and all downloads patched to 3.2.0.3 which includes the fix:

http://dotnetblogengine.net/post/patch-for-blogengine-net-3-2.aspx

**Comment by jijiechen** [comment]
Many thanks.
