### ISSUE TITLE
PreCompile Error!

### ISSUE THREAD

**Issue by PerseusTheGreat** [rxtur/BlogEngine.NET#32]
Hi there.

Where is `App_Code.Controls.WidgetContainer`?

When I tried to compile BE.NET (with pricompilation enabled option), asp.net compiler has reported some errors about `Widget` in all `WidgetContainer.ascx` in custom\theme\ subfolders.
> Error CS0103 The name 'Widget' does not exist in the current context

Please do precompilation and fix all issue, or guide me to fix them.

Regards.

**Comment by rxtur** [comment]
Fixed.

**Comment by PerseusTheGreat** [comment]
Thanks a lot.
