### ISSUE TITLE
RSS feeds not displaying correctly when not logged into the blog (single user, single blog configuration)

### ISSUE THREAD

**Issue by Cambridgeport90** [rxtur/BlogEngine.NET#33]
Hi all, 
Not sure whether this is my fault or not, but I evidently don't know how to set up RSS feeds correctly in the latest release of Blog Engine (the default URL only seems to display correctly for logged in users (for non logged in members, just displays a page full of XML)). What is the correct URL? And also, how does one set it up for multiple categories? If I wanted to allow people to only subscribe to a particular category, for instance. Thanks.

**Comment by rxtur** [comment]
Most likely date published issue for both posts and RSS. Try to set up time zone in settings so that when publish post, date/time published same as your local time.

**Comment by Cambridgeport90** [comment]
I’ve already ensured accuracy on that. What I can’t figure out is the actual URL that is supposed to appear in settings so that I can feed it into other services, or so that people can subscribe to it. The current one is: 

http://cambridgeport90.net/syndication.axd

Speaking of posts being published, I just published one this evening, and the one from both today and from last week aren’t visible when not logged in. Not sure what that has to do with RSS though … Anyway, thanks for the tips.

**Comment by Cambridgeport90** [comment]
Changing the time offset to UTC Eastern Standard time didn’t change anything.

**Comment by rxtur** [comment]
You need to insure when you publish post, it is immanently visible to public.
1. set time zone to -10, publish, log off and verify it is visible.
2. if not visible, set time zone to +10, publish, log off and verify it is visible.

If both cases don't work, we have an issue. 
If one of them works, you just need to adjust to correct zone. Which is not necessarily your real time zone - for this your server need to be set to use UTC time and it may not be. I know it is confusing, even wrote a post on it some time ago: http://www.rtur.net/blog/post/2015/09/04/crazy-fun-times

**Comment by Cambridgeport90** [comment]
I’ll do that. Thanks for reminding me of that post. The server though, I can tell you is Eastern Standard time.

**Comment by Cambridgeport90** [comment]
Neither plus or minus ten hours works. Just tried it, and none of the posts, except for the very first one, are publically visible. Yet I can see them while logged in.

**Comment by rxtur** [comment]
Another duplicate (#42)
