### ISSUE TITLE
multi blog enabling

### ISSUE THREAD

**Issue by rikenmon** [rxtur/BlogEngine.NET#35]
After someone hacked my blog  (3.1.1) it stopped working. Now I try to make a new blog (3.2) but I use multi (2) blogs. However in the the latest blog version I can not find the way to use multi blog again.

How to switch on multi blog or is it just gone?

Thanks in advance for any tips!

**Comment by goranhell** [comment]
https://github.com/rxtur/BlogEngine.NET/wiki/Configuration

**Comment by rikenmon** [comment]
Hello,

unfortunately you closed is. I found after switching to multi blog some errors in:
 
be_WIDGET_ZONE.xml causing an error in the secondary blogs.

Can you look at that?

Thanks for the help so fart and keep the good work going,




Erik Severiens
