### ISSUE TITLE
pros and cons for Add Date to Post Links?

### ISSUE THREAD

**Issue by joeaudette** [rxtur/BlogEngine.NET#38]
Hi All,

Hope it is ok to ask questions here, this is not an "issue" per se. If there is a different place I should post questions please let me know.

What I'm wondering about is what is the current consensus/wisdom about post dates in urls? The default is to not use them and I wonder is that the recommended way. When setting up a new blog I think one needs to make a decision about that early and stick with the decision later because the urls should not change.

I can see how shorter urls can be cleaner and in some cases the date of the post is not important whereas in others it might be such as in technology review posts where you might want it to be clear years later that the review is of old devices.
The other potential benefit I see with dates in the url is if the urls could be hackable so that /posts/year would show the list of posts for the year and /posts/year/month would show a lists of posts from the given year and month. When I enable dates it doesn't seem that they are hackable urls, I just get a 404 if I remove parts of the url. Is this not possible in BlogEngine.NET? has the idea of hackable urls gone out of style?

Thanks for any advice, wisdom or guidance.

Joe

**Comment by rxtur** [comment]
We used to include date by default, and #1 question on forums was how to remove it :)

I don't know if conventional wisdom cares much, but here is strong opinion for including:
http://www.wpbeginner.com/opinion/why-you-should-not-remove-dates-from-your-wordpress-blog-posts/

My personal take is include if you have large content and want to play safe with SEO, don't bother if you have small personal blog and like pretty simple URLs that easy to share.

**Comment by joeaudette** [comment]
Thanks for replying!
I recently read that post while researching about urls and that is actually the very article that got me wondering whether it would be better in the long run to include the dates. It seems like the trend moved away from including dates in the url which is perhaps why it was the #1 question. That article got me thinking maybe the herd has headed in the wrong direction by going without the dates and maybe the trend is heading back toward including the dates. That article seems to indicate that people started not only removing the  dates from the urls but also not even showing the pub date in the UI so that the content always seems recent or relevant in search results. I definitely want to show the pubdate in the UI and I'm leaning towards also in the url.

But if I do include the dates in the urls is there any way to make the urls hackable so that archives can be found by hacking the year and month in the url? To me if the dates are in the url it kind of invites hacking the url.

**Comment by Cambridgeport90** [comment]
Thanks,, guys for the advice on this. I'l take that into consideration. I'm in the process of moving my Blog back to this anyway.

**Comment by rxtur** [comment]
Clean up - not an issue, belongs to forums (https://blogengine.codeplex.com/discussions)
