### ISSUE TITLE
Advanced option not available under settings

### ISSUE THREAD

**Issue by abhilashca** [rxtur/BlogEngine.NET#39]
Hi,

Advanced option is not visible directly under settings menu. But, is available only when we make manual edit to the URL (by replacing admin/#/settings/basic with admin/#/settings/advanced). Is that purposefully made hidden?

Thanks.

**Comment by rxtur** [comment]
Yes, please refer to: https://github.com/rxtur/BlogEngine.NET/wiki/Configuration
