### ISSUE TITLE
Blog posts only show up to logged in users after the first one

### ISSUE THREAD

**Issue by Cambridgeport90** [rxtur/BlogEngine.NET#40]
Not sure how this happened, but it was unfortunately my reason for going away from Blog Engine, but when I'd make a post and click publish, I could clearly see that the post went through, though only when logged in, and it was not curated via RSS distribution services. Wonder how that happened. It seems to have occurred after messing with the time offset, which, I'd never fully understood in the first place.

**Comment by rxtur** [comment]
I assume that, running blog locally, you don't have this issue. But publishing to the server has long delay. This has nothing to do with RSS, you only see posts because authenticated users can see drafts, even unpublished.

What is your client (local) time zone, server time zone and what offset time selected in settings?
I need to be able to re-create what you are doing to address this.

**Comment by Cambridgeport90** [comment]
This is running things from a remote browser, (Firefox), my client and server’s timezones are set to EST, while the offset is set to EST as well (-5:00).

**Comment by rxtur** [comment]
Is this your dedicated server? Can you set server time to use UTC universal (0)?

I'll check you setup later today, but pretty sure if you can set server to UTC that will fix it right away.

**Comment by Cambridgeport90** [comment]
Sure I can, though it might be confusing once she joins Active Directory … I’ll try that and see what happens.

**Comment by Cambridgeport90** [comment]
Something else I forgot to mention. My web server, while dedicated, it’s also part of my domain. How then do we deal with this time issue. I’d hate to have the IIS server off the domain due to a time difference.

**Comment by rxtur** [comment]
Somehow I have different issue - no matter what time I use on client and server, it always set correct published time and works fine for logged in and anonymous user. Need to troubleshoot more.

**Comment by sqc1999** [comment]
@rxtur Please see BlogSettings.ToUtc, it tries to convert the `localTime` using server side timezone.

**Comment by rxtur** [comment]
Duplicate issue (https://github.com/rxtur/BlogEngine.NET/issues/42)
