### ISSUE TITLE
Import RSS from BE2.9 to BE3.2 failing

### ISSUE THREAD

**Issue by abhilashca** [rxtur/BlogEngine.NET#47]
Hello,

I am trying to import RSS feed from my blog (BE v2.9) to BE v3.2. But, it is failing with error -  "**The request failed with HTTP status 404: Not found"**. I used click-one importer to achieve the import task. In the Source information, I provided my blog information (hosted) and BE v3.2 was hosted in my local machine which is provided as Destination information. I hope, this is the right way to do it.

![be_v32_import_error](https://cloud.githubusercontent.com/assets/12084395/13899490/bc1ef814-ee15-11e5-8003-a0f339523440.png)

When I tried validating Destination information, I got blog validation error.

![be_v32_import_error_2](https://cloud.githubusercontent.com/assets/12084395/13899498/e316459e-ee15-11e5-932e-9c60d038c0a9.png)

Though the import failed, I noticed one very surprising thing. All my draft post become published automatically (which I have to delete manually!). I still wonder, how did that happened?

I also tried importing blogML to BE v3.2 but the effect was same.

Please note, I haven't done any manual edits to the blog. Am I doing the import functionality in it's recommended way? Any help will be appreciated.
Thanks.

**Comment by abhilashca** [comment]
Am I lost here?

**Comment by rxtur** [comment]
Click one is 3rd party application, not even sure if there is source code for it.

Try to export to BlogML and then import into 3.2.
Or just copy files from app_data into new blog, no data format changes between 2.9 and 3.2.

**Comment by abhilashca** [comment]
I tried importing BlogML, but it didn't worked. When I selected the BlogML file, the page refreshed and redirected to Dashboard. No blog posts are imported. Is that a bug?

Below is my BE specification.
![be_spec](https://cloud.githubusercontent.com/assets/12084395/14025276/5416fda0-f213-11e5-8c4d-d45f3e38eb6f.png)

Thanks.

**Comment by abhilashca** [comment]
Below is the error from log file
![be_log_error](https://cloud.githubusercontent.com/assets/12084395/14026182/b565e036-f217-11e5-9dc1-be65f546d9a7.png)

**Comment by rxtur** [comment]
Send me your BlogML file so I can try it. It can be content specific - something in exported posts not parsed correctly. (rtur dot net at gmail).

**Comment by abhilashca** [comment]
Thanks. I really appreciate your effort. I have emailed BlogML.

**Comment by abhilashca** [comment]
I could successfully import the BlogML to BE3.1. Looks like the issue is with BE3.2.
I got one doubt as well. After importing the BlogML contents, I only need to copy contents from old_blog\app_data\files to  new_blog\app_data\files, right? Do I need to do anything other than that?

Thanks in advance.

**Comment by rxtur** [comment]
Well you also need to update app_data/categories.xml and sync post author(s) if not already.

**Comment by abhilashca** [comment]
Not sure how, both categories and tag cloud are showing in imported blog. Looks like BlogML has imported those contents as well. Is that not the case?

Regarding post authors, I create new author with same name and all the old posts are showing under that author's name. I assume the author's name is unique here and not any author Id.Is that so?

Thanks.
