### ISSUE TITLE
GalaxyBlog - not working

### ISSUE THREAD

**Issue by alexandrudanpop** [rxtur/BlogEngine.NET#48]
BE 3.2 Repo cloned today:
Steps to reproduce:
Go to Admin > Custom > Themes > Download GalaxyBlog > View Blog.

Parser Error

Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

Parser Error Message: Unknown server tag 'blog:SearchBox'.

Source Error: 
Line 81:                     blog:SearchBox ID="SearchBox1" runat="Server" 

Source File: /Custom/Themes/GalaxyBlog/site.master    Line: 81

**Comment by alexandrudanpop** [comment]
Same thing for SimpleBlog Theme. 
Deleting that line in  /Custom/Themes/..themename../site.master and rebuilding solution fixed the issue for both themes for me.

**Comment by sqc1999** [comment]
There are a lot of themes using blog:SearchBox and not working.

**Comment by rxtur** [comment]
Current code changes intended to move widgets from WebForms completely, this step is to prepare BE moving to MVC in the next version. So all WebForms controls must go away. If theme uses controls, it has to be updated to support BE 3.3.
