### ISSUE TITLE
Users Menu not found in admin

### ISSUE THREAD

**Issue by mayurlohite** [rxtur/BlogEngine.NET#49]
Hello I installed blogengine  but when I logged in as Admin I never found the "USERS" menu in left side.
What is this issue?

**Comment by Cambridgeport90** [comment]
If you don’t set that property in web.config, then it won’t show. The default install is single-blog, single-user.

**Comment by mayurlohite** [comment]
Oops!!! Sorry My bad !!! I haven't seen it.
