### ISSUE TITLE
Error when using mysql config

### ISSUE THREAD

**Issue by scrummie02** [rxtur/BlogEngine.NET#5]
Server Error in '/' Application.
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

    Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error:

    Line 6:      var profile = AuthorProfile.GetProfile(name);
    Line 7:  
    Line 8:      var src = profile.PhotoUrl;
    Line 9:      if (string.IsNullOrEmpty(src))
    Line 10:     {

Source File: z:\owncloud\MyDocs\Documents\Visual Studio\BlogEngine.NET-master\BlogEngine\BlogEngine.NET\admin\themes\standard\sidebar.cshtml    Line: 8
    [NullReferenceException: Object reference not set to an instance of an object.]
   ASP._Page_admin_themes_standard_sidebar_cshtml.Execute() in z:\owncloud\MyDocs\Documents\Visual Studio\BlogEngine.NET-master\BlogEngine\BlogEngine.NET\admin\themes\standard\sidebar.cshtml:8
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +198
   System.Web.WebPages.WebPage.ExecutePageHierarchy(IEnumerable`1 executors) +69
   System.Web.WebPages.WebPage.ExecutePageHierarchy() +131
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +90
   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +233
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   ASP._Page_admin_themes_standard_layout_cshtml.Execute() in z:\owncloud\MyDocs\Documents\Visual Studio\BlogEngine.NET-master\BlogEngine\BlogEngine.NET\admin\themes\standard\layout.cshtml:58
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +198
   System.Web.WebPages.WebPage.ExecutePageHierarchy(IEnumerable`1 executors) +69
   System.Web.WebPages.WebPage.ExecutePageHierarchy() +131
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +90
   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +233
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +63
   System.Web.WebPages.WebPageBase.PopContext() +237
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +98
   System.Web.WebPages.WebPageHttpHandler.ProcessRequestInternal(HttpContextBase httpContext) +116

**Comment by rxtur** [comment]
The MySql config not yet converted to new version, I'll do it in the next few days when have a chance.

**Comment by scrummie02** [comment]
Working with Andy on codeplex he found a possible solution. I've also made some changes to the web.config for mysql because it wasn't converted yet.  I'll submit the changes.

**Comment by rxtur** [comment]
Config file modified and tested.
