### ISSUE TITLE
Issue in DashboardController

### ISSUE THREAD

**Issue by sqc1999** [rxtur/BlogEngine.NET#50]
I created a user and put it into the Editor role which is authorized to view dash dashboard by default. But when I tried to access the dashboard, `error getting stats` is showed.
I tried this again with visual studio debugger attached and found out the problem. In `DashboardController.cs, line 14`, the code is checking rights for viewing admin settings page, but not dashboard.

**Comment by rxtur** [comment]
Fixed in 3.2.2.3
