### ISSUE TITLE
Is there a way to change roles for already created user?

### ISSUE THREAD

**Issue by sqc1999** [rxtur/BlogEngine.NET#51]
I looked for it in the settings but could not find anything related to this.

**Comment by rxtur** [comment]
https://github.com/rxtur/BlogEngine.NET/wiki/Configuration

**Comment by sqc1999** [comment]
I've added `<add key="BlogEngine.UsageScenario" value="multiusers" />` to my Web.config but this has no effect.

**Comment by rxtur** [comment]
It didn't add "security" menu with "users" and "roles"? Or you expected some other effect?

**Comment by sqc1999** [comment]
I can add users and roles.
I can select roles when creating a new user, but I can't change that later. Is it supported?

**Comment by rxtur** [comment]
No this is not supported. You can delete user and create new with different role if needed.
