### ISSUE TITLE
Not able to embed github gist to post

### ISSUE THREAD

**Issue by mayurlohite** [rxtur/BlogEngine.NET#56]
I think due to XSS filter <script> tag is prohibited in the post. Is there any trick to embed github gist to post?

Thank you.

**Comment by sqc1999** [comment]
GitHub Gist provides jsonp support, you can use `https://gist.github.com/sqc1999/{gist_id}.jsonp`.

**Comment by mayurlohite** [comment]
Sorry!!!
But please can you explain me how I embed it to my blog?

**Comment by sqc1999** [comment]
Just write a piece of javascript code to perform Ajax requests and parse the responses.
Or you can just use a existing project [gist-embed](https://github.com/blairvanderhoof/gist-embed).

**Comment by mayurlohite** [comment]
Okie Got it :)
