### ISSUE TITLE
the issue on get_tags.

### ISSUE THREAD

**Issue by trucnguyensk** [rxtur/BlogEngine.NET#63]
I has added tags on my Post, then click save button. It hasn't affected to database :)

**Comment by trucnguyensk** [comment]
I had debugged on this. I saw the problem on tags control of posts content.

**Comment by rxtur** [comment]
I have no problem adding and saving tags to the post with MS SQL server. Are you just typing tag and click save? Cause you need to hit "enter" after you type, you know :)

**Comment by trucnguyensk** [comment]
yep, you right!. I typed and out-focus this textbox. I forgot to press 'enter'. I think the event effect when is out-focus :) . Thank you
