### ISSUE TITLE
I don't think table be_Roles needs a data column BlogID.

### ISSUE THREAD

**Issue by yw80** [rxtur/BlogEngine.NET#64]
This problem involves 3 tables:
be_Roles ( RoleID, BlogID, Role )
be_Rights ( RightRowId, BlogId, RightName )
be_RightRoles ( RightRoleRowId, BlogId, RightName, Role )

In these three tables, each table has a data column BlogId. I don't think this data column BlogId is necessary, no matter which of the three kinds of scenarios.

**Comment by rxtur** [comment]
I have a blog called "zoo" and I want a role "zoo keeper" which should not be visible to other blogs. How do I do this without blog ID in the roles table?

**Comment by yw80** [comment]
Thank you for your reply.

I'm sure I understand what you mean, and in the old version BlogEngine there's going to be what you say. 

But in current version BlogEngine, multiblogs scenario clear definition for "every blog only one author" (see: https://github.com/rxtur/BlogEngine.NET/wiki/Configuration). This is not necessary to define a role which only belongs to a blog, because the blog owner cannot create a new user based on the role.

I set the scenario for multiblogs, "USERS - > Roles" menu is not visible, it only appeared in the multiusers scenario. But in the multiusers scenario, there is only one blog, and thus the data column BlogID is not necessary, too.

BTW, I like the new version of the scenarios definition.

**Comment by rxtur** [comment]
Eventually single membership will be enforced and UI refined, for now this is definitely not an issue but rather possible refactoring opportunity that will be looked into down the road.
