### ISSUE TITLE
Set Custom fields key list in web.config which may be more practical

### ISSUE THREAD

**Issue by yw80** [rxtur/BlogEngine.NET#66]
At present, the author can add Custom fields when write articles, and the website files need to be modified at the same time. Otherwise, the Custom fields will not be displayed on the page.
However, the authors do not have the right to modify the website files.

So, if we set the Custom fileds key list in web.config, will be better?

Web.config maintenance, and the maintenance of the website file, is the programmer's work. These jobs need to be done before the website online. The authors only need to fill in these fields when writing the article.

**Comment by rxtur** [comment]
Need to clarify on the issue - this is what I'm trying to do and this is result I expect but don't get. Otherwise it looks like feature request and don't belong here.
