### ISSUE TITLE
Error on write operation - how to get detailed error message

### ISSUE THREAD

**Issue by abhilashca** [rxtur/BlogEngine.NET#67]
Hello,

I am facing a weird problem with hosted BE blog (v3.1.0.1). I am unable to make any write operations (like approving comments, deleting comments, purge log messages, etc.) from my _hosted_ blog. Whenever, I try to do so, the write operations fails and shows an error message as below:

![write_error](https://cloud.githubusercontent.com/assets/12084395/15025671/06981fa4-1258-11e6-9943-0cb84e44b8fa.png)

The issue exists only when I try to make any write operation from my _hosted_ blog. when I host the same blog locally in my machine, I am not facing any issues. I guess some settings in my hosted webportal is causing this issue. I have given write permission to App_Data directory but still the issue is not resolved.

Interesting thing I noted is, when I get failed message during write operation failure, no error message is logged in the logger. How can I see the detailed error message? Is that possible? Do I need to enable anything in web.config before hosting the blog?

Any help will be appreciated.
Thanks.

**Comment by abhilashca** [comment]
Can somebody help me out here?

**Comment by sqc1999** [comment]
I suggest you write a aspx page that writes to the App_Data directory and outputs detailed error message to test if you really have write permission in your hosting environment.

**Comment by sqc1999** [comment]
Also check if your trust level is high enough. You can't write to the file system if the level <=  `Low`.
You can see your trust level settings in http/https://yoursite/admin/about.cshtml.
See the [MSDN document](https://msdn.microsoft.com/en-us/library/tkscy493(v=vs.85).aspx) for more information.

**Comment by rxtur** [comment]
This is for current code issues, should be able to reproduce with latest code.
