### ISSUE TITLE
ng-click still fires with ng-disabled set to true

### ISSUE THREAD

**Issue by sqc1999** [rxtur/BlogEngine.NET#69]
`ng-disabled ` works fine with `<button>` tags, but with others(e.g. `<a>` tags used in BlogEngine.NET), it will not stop the execution of `ng-click`. So if I click a disabled button, the corresponding function is still called.
See https://baudehlo.com/2014/02/24/angular-js-ng-click-still-fires-when-div-is-ngdisabled/ for more information.

**Comment by rxtur** [comment]
Fixed with 3.3.0.2
