### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by goranhell** [rxtur/BlogEngine.NET#73]
Using RSS 2 as feed format doesn't work for my Culture (swedish). The pubdata comes out wrong.
Haven't checked but I guess that this would fix the problem (in SyndicationGenerator.cs)

`        static string RssDateString(DateTime pubDate)
        {
            pubDate = BlogSettings.Instance.FromUtc(pubDate);
            var value = pubDate.ToString("ddd',' d MMM yyyy HH':'mm':'ss",  System.Globalization.CultureInfo.CreateSpecificCulture("en-US")) + " " +
                pubDate.ToString("zzzz").Replace(":", "");
            return value;
        }
`

**Comment by rxtur** [comment]
Can't check it with Swedish but should be fixed in 3.3.0.5
