### ISSUE TITLE
Can't use flatblog theme with newest blogengine release

### ISSUE THREAD

**Issue by scrummie02** [rxtur/BlogEngine.NET#80]
I was going to update my blogengine installation to the latest available on github, but when I use the flatblog theme the widgets show up but no CSS.  I saw a few days ago this issue was being addressed but can't seem to find the pull requests.  I know the widgets have changed, what do I need to change in my CSS settings?

**Comment by rxtur** [comment]
Should work with 3.3.0.1

**Comment by scrummie02** [comment]
Thanks, this works 

Get Outlook for iOS




On Wed, May 18, 2016 at 7:56 PM -0700, "rxtur" <notifications@github.com> wrote:












Should work with 3.3.0.1
