### ISSUE TITLE
Textbox Widget doesn't like the apostrophe char entity

### ISSUE THREAD

**Issue by dg2k** [rxtur/BlogEngine.NET#81]
An apostrophe **&#39;** character (which shows up as an entity char code **&#****39;** after encoding), if typed into a Textbox Widget triggers the *HttpRequestValidationException* upon validating a Response. This happens [here ](https://github.com/rxtur/BlogEngine.NET/blob/master/BlogEngine/BlogEngine.NET/Custom/Widgets/TextBox/edit.cshtml#L9) in the code, and obviously the innocent apostrophe is misinterpreted as some dangerous code injection.

I was thinking of a pull request but also thought the original author will have a better way of fixing this far quicker with better maintainability in mind (because I am still learning the anatomy of BlogEngine.Net). (Sure I can quickly create an exception (no pun intended) for an apostrophe using try-catch blocks but I know that is not a nice fix at all).

Hope this helps.

**Comment by rxtur** [comment]
Fixed with 3.3.0.3
