### ISSUE TITLE
Published posts are not visible for guest users?

### ISSUE THREAD

**Issue by kamil-mrzyglod** [rxtur/BlogEngine.NET#87]
Configuration:

Version: 3.3.0.0
Configuration: Single blog
Trust level: Unrestricted
Identity: IIS APPPOOL\Blog
Blog provider: XmlBlogProvider
Membership provider: XmlMembershipProvider
Role provider: XmlRoleProvider

Steps to reproduce:
- Log in as an admin user
- Got to the Content - Posts - New page
- Insert a title, add some text for a post, select a category, select keywords
- Click on the 'Publish' button

Post should be visible for all the users. Unfortunately it is not.

Tomorrow I can try to get some more details if possible.

**Comment by rxtur** [comment]
Can't recreate, please provide details if still an issue.

**Comment by kamil-mrzyglod** [comment]
Hi,

I've faced this strange issue once more, now I reproduced it on my local PC.

Steps:
1. Create a fresh instance of a blog
2. Log in as admin/admin
3. Add a new post with a custom category(just click 'Publish')
4. Log out

Expected:
Post should be visible

Actual: 
Post is not visible

Note that as a guest user I see posts added to the blog by default. Basically the problem is in `PostList.aspx.cs` file in line 107:

`var visiblePosts = this.Posts.FindAll(p => p.IsVisible);`

Each new post has this property set to `false`. Going further, problem lies in `Post.cs` file in line 669 where this property is implemented:

```
public bool IsVisible
        {
            get
            {
                if (this.IsDeleted)
                    return false;
                else if (this.IsPublished && this.DateCreated <= BlogSettings.Instance.FromUtc())
                    return true;
                else if (Security.IsAuthorizedTo(Rights.ViewUnpublishedPosts))
                    return true;

                return false;
            }
        }
```

the flow goes to the security check when it shouldn't because post is published. After some time blog post appears because `this.DateCreated <= BlogSettings.Instance.FromUtc()` is finally true.

So it seems it is caused when there is a timezone set to the default value and I am in the different one(+1 in my specific case).

I'm not sure whether it's a defect, but for sure it's a bit confusing one :)

**Comment by mrrrk** [comment]
I found the same.  To fix:

- Log in
- Go to Admin -> Settings -> Basic
- Change timezone from "(UTC) Coordinated Universal Time" to whatever your local timezone is.

In may case, I changed it to "(UTC) Dublin, Edinburgh, Lisbon, London" to take into account daylight savings.  Presumably if I'd left it, the post would have appeared an hour later!

**Comment by sathishinwebz** [comment]
> I found the same. To fix:
> 
> * Log in
> * Go to Admin -> Settings -> Basic
> * Change timezone from "(UTC) Coordinated Universal Time" to whatever your local timezone is.
> 
> In may case, I changed it to "(UTC) Dublin, Edinburgh, Lisbon, London" to take into account daylight savings. Presumably if I'd left it, the post would have appeared an hour later!

I was trying different options for two hours....and this was resolved my issue.
