### ISSUE TITLE
History of Repository/Project in readme

### ISSUE THREAD

**Issue by aaronhoffman** [rxtur/BlogEngine.NET#9]
Hello @rxtur,

I am assuming this is a "fork" of this project https://blogengine.codeplex.com/. As that page does not reference this repo, would you be able to add some information to the readme explaining the relationship if any to the codeplex project and the history of this fork. Thanks!

**Comment by scrummie02** [comment]
Read Rtur's blog.  He talks about the move from codeplex to github 

Sent from Outlook




On Fri, Nov 13, 2015 at 10:55 AM -0800, "Aaron Hoffman" <notifications@github.com> wrote:












Hello @rxtur,



I am assuming this is a "fork" of this project https://blogengine.codeplex.com/. As that page does not reference this repo, would you be able to add some information to the readme explaining the relationship if any to the codeplex project and the history of this fork. Thanks!

**Comment by kbdavis07** [comment]
Hi @aaronhoffman,

This explains 😀

http://www.rtur.net/blog/post/2015/08/25/sneak-peek-on-blogengine-2015

**Comment by rxtur** [comment]
Readme updated, also added pointer to repository in the Codeplex
