### ISSUE TITLE
bugs on admin panel 

### ISSUE THREAD

**Issue by alessandro-diez** [rxtur/BlogEngine.NET#90]
when logging out via 
[http://zoo.azurewebsites.net/Account/login.aspx?logoff](http://zoo.azurewebsites.net/Account/login.aspx?logoff)
and then going back with the browser the pages are still accessible, toastr is just giving some error messages about error loading content/settings etc.
on 
[http://zoo.azurewebsites.net/admin/#/content/tags](http://zoo.azurewebsites.net/admin/#/content/tags)
hitting delete without anything selected will make the content page disappear

**Comment by rxtur** [comment]
Second issue fixed with 3.3.0.2
The first issue I don't see - either it was fixed or it only true for some conditions I can't recreate.

**Comment by sqc1999** [comment]
@alessandro-diez For your first issue, did you mean go back using the go back button on the browser? If so, the browser will not perform a request to the server but read from the cache, so it doesn't know it is not accessible now. But the contents in the page are loaded via AJAX, so the browser won't simply use the cache, and receive an error from the server.
