### ISSUE TITLE
Option to export blog is missing from settings in BlogEngine.NET 3.3

### ISSUE THREAD

**Issue by craigtp** [rxtur/BlogEngine.NET#92]
There used to exist options for importing or exporting the content of a blog, in BlogML format, within the admin "Settings" page.  This option seems to be missing from BlogEngine.NET version 3.3 (possibly earlier versions also).

Please re-instate the ability to import/export blog contents.

**Comment by goranhell** [comment]
Don't really not know why, but....

in BlogEngine.NET/admin/themes/standard/sidebar.cshtml in line 90, change
`@if (BlogConfig.UsageScenario != "singleblog" && Blog.CurrentInstance.IsPrimary)`
to
`@if (Blog.CurrentInstance.IsPrimary)`

**Comment by rxtur** [comment]
It is under "advanced" and hidden for simple single user configuration.
