### ISSUE TITLE
Incorrect name "RegisterDiCintainer"

### ISSUE THREAD

**Issue by kCoderC** [rxtur/BlogEngine.NET#93]
In the file "**BlogEngineConfig.cs**" the method name should be "**RegisterDiContainer**" instead of "**RegisterDiCintainer**", or could be renamed to '**ConfigIocContainer**'.

Also the container instance should be declared outside of the method, maybe in the BlogEngineConfig class or some sort of **_`Façade`_** service class in case we need to resolve something in the **_`composite root`_** (Global.asax, static service classes, ... ) .

**Comment by rxtur** [comment]
Fixed with 3.3.0.2

**Comment by kCoderC** [comment]
Thank you for your time, and sorry for my late response.
