### ISSUE TITLE
page 404 not open

### ISSUE THREAD

**Issue by MJ-Vakili** [rxtur/BlogEngine.NET#96]
HIi,
page error404.aspx not open.
e.g:
http://dotnetblogengine.net/sdfsdfsdf
http://dotnetblogengine.net/sdfjsdf.aspx

**Comment by sqc1999** [comment]
This is an miss configured setting in the `web.config` file on the server of dotnetblogengine.net, but not an issue in the project. I think it'll be better to edit the tittle to clarify this.

**Comment by rxtur** [comment]
This was added to web.config and should fix 404 custom error page in IIS.

` <httpErrors existingResponse="Replace" errorMode="Custom">
        <remove statusCode="404" subStatusCode="-1" />
        <error statusCode="404" prefixLanguageFilePath="" path="/error404.aspx" responseMode="ExecuteURL" />
    </httpErrors>`
