### ISSUE TITLE
Trailing / on sub blog and pager control/url handling

### ISSUE THREAD

**Issue by DotNetWorker** [rxtur/BlogEngine.NET#99]
If the user navigates to the blog from a link with no trailing / as is natural to do and then attempts to use the pager to page to next page of posts, 404 occurs. If a trailing / is inserted after the url and attempt to page it works fine. 
Had this reported by a few users of my site, also means being careful when I hyperlink to the site that the slash has to be included or the next navigation on the pager will fail.

URLs generated by pager control: 
http://www.yoursite.com/sublog?page=3
**Causes 404 Not found**

http://www.yoursite.com/sublog/?page=3
**Works correctly**

**Comment by rxtur** [comment]
Fixed in commit 2e5cc82eaa350ff0938a57258407e3d6b0186d6c
